<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="19310" started-at="2020-01-20T13:23:38 EST" finished-at="2020-01-20T13:23:58 EST">
    <groups>
      <group name="regression">
        <method signature="LoginAndTitle.logoValidation()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="logoValidation" class="com.class04.LoginAndTitle"/>
        <method signature="LoginAndTitle.titleValidation()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="titleValidation" class="com.class04.LoginAndTitle"/>
      </group> <!-- regression -->
    </groups>
    <test name="Default test" duration-ms="19310" started-at="2020-01-20T13:23:38 EST" finished-at="2020-01-20T13:23:58 EST">
      <class name="com.class04.LoginAndTitle">
        <test-method status="PASS" signature="openAndNavigate()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="openAndNavigate" is-config="true" duration-ms="11655" started-at="2020-01-20T13:23:39 EST" finished-at="2020-01-20T13:23:50 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAndNavigate -->
        <test-method status="FAIL" signature="logoValidation()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="logoValidation" duration-ms="3432" started-at="2020-01-20T13:23:50 EST" finished-at="2020-01-20T13:23:54 EST">
          <exception class="org.openqa.selenium.NoSuchElementException">
            <message>
              <![CDATA[Cannot locate an element using xpath=//div[@id='divLogo']/img
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'Ayleens-Air.fios-router.home', ip: 'fe80:0:0:0:1cb8:1546:dc81:7e47%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.2', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.NoSuchElementException: Cannot locate an element using xpath=//div[@id='divLogo']/img
For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:48'
System info: host: 'Ayleens-Air.fios-router.home', ip: 'fe80:0:0:0:1cb8:1546:dc81:7e47%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.15.2', java.version: '1.8.0_221'
Driver info: driver.version: RemoteWebDriver
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:327)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at com.class04.LoginAndTitle.logoValidation(LoginAndTitle.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.NoSuchElementException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoValidation -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="closeBrowser" is-config="true" duration-ms="152" started-at="2020-01-20T13:23:54 EST" finished-at="2020-01-20T13:23:54 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="openAndNavigate()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="openAndNavigate" is-config="true" duration-ms="3751" started-at="2020-01-20T13:23:54 EST" finished-at="2020-01-20T13:23:58 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openAndNavigate -->
        <test-method status="FAIL" signature="titleValidation()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="titleValidation" duration-ms="42" started-at="2020-01-20T13:23:58 EST" finished-at="2020-01-20T13:23:58 EST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Titles are NOT matched expected [Human Management Systems] but found [404 Not Found]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Titles are NOT matched expected [Human Management Systems] but found [404 Not Found]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.class04.LoginAndTitle.titleValidation(LoginAndTitle.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- titleValidation -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.class04.LoginAndTitle@1f28c152]" name="closeBrowser" is-config="true" duration-ms="170" started-at="2020-01-20T13:23:58 EST" finished-at="2020-01-20T13:23:58 EST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.class04.LoginAndTitle -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
